Return offset when parent is matched
corpus-io/Ccip-Resolver pull request #46
Opened 2023-09-04 16:18 UTC by makoto

Address https://github.com/corpus-io/Ccip-Resolver/issues/45

2023-09-04 16:22 UTC, AlexNi245 approved these changes

2023-09-04 16:35 UTC, makoto commented
this is actually not good enough. Also has to support when `alice.eth` uses default verifier

2023-09-05 14:52 UTC, AlexNi245 commented on contracts/ERC3668Resolver.sol
> +        console.log('metadata');
please remove all console.logs

2023-09-05 14:55 UTC, AlexNi245 requested changes
see comments

2023-09-06 07:40 UTC, AlexNi245 approved these changes

2023-09-06 12:52 UTC, merged