Multiple proofs
corpus-io/Ccip-Resolver pull request #51
Opened 2023-09-07 17:01 UTC by AlexNi245

2023-09-07 17:03 UTC, AlexNi245 commented on test/gateway/signatureHandler.test.ts
> +        const expected = ethers.utils.hexlify(vitalik.address);
@hai-ko this shows how to format the address

2023-09-08 07:16 UTC, hai-ko requested changes

2023-09-08 07:16 UTC, hai-ko commented on test/e2e/optimismBedrockHandler.test.ts
> +    it.only('Returns valid string data from resolver', async () => {
remove `.only`

2023-09-08 07:16 UTC, hai-ko commented on test/gateway/signatureHandler.test.ts
> +    it.only('Returns valid address from resolver', async () => {
remove `.only`

2023-09-08 07:22 UTC, merged